#%RAML 1.0
title: Banking Accounts Process API
version: v1.0
baseUri: http://localhost:8081/api

types:
  Account: !include dataTypes/Account.raml
  AccountOwner: !include dataTypes/AccountOwner.raml
  Address: !include dataTypes/Address.raml
  Bank: !include dataTypes/Bank.raml
  Metadata: !include dataTypes/Metadata.raml
  Money: !include dataTypes/Money.raml
  Transaction: !include dataTypes/Transaction.raml
  TransactionDetails: !include dataTypes/TransactionDetails.raml
  User: !include dataTypes/User.raml

/accounts/aggregate:
  displayName: Aggregate user accounts
  get:
    description: Return aggregated Accounts of user specified by SSN  
    queryParameters:
      ssn:
        type: string | integer
        example: "124-123-12344"
    responses:
      200:
        body:
          application/json:
            type: Account[]
            example: !include ./examples/get_accounts_aggregate_example.json
/transactions/aggregate:
  displayName: Aggregate user transactions
  get:
    description: Return aggregated Transactions of user specified by SSN  
    queryParameters:
      ssn:
        type: string | integer
        example: "124-123-12344"
    responses:
      200:
        body:
          application/json:
            type: Transaction[]
            example: !include ./examples/get_transactions_aggregate_example.json